### ISSUE TITLE
crash with viafabricplus

### ISSUE THREAD

**Issue by Moonyol** [RelativityMC/raknetify#53] opened 2024-08-18 08:45 UTC
**Describe the bug**
Clicking the multiplayer menu with viafabricplus installed crashes the game

**To Reproduce**
1. get raknetify and viafabricplus
2. launch the game and click multiplayer
3. crash

**Expected behavior**

it is supposed to not crash

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Linux
 - Minecraft version: 1.20.4
 - Mod version: raknetify-fabric-0.1.0+alpha.5.128-all.jar

**Crash reports / logs**

https://pastebin.com/kCcHcDSs

**Other mods**

![image](https://github.com/user-attachments/assets/8cdeec14-3208-46bc-95ca-e9506a78a37b)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

fabric 0.16.0

**Comment by ishland** [comment] 2024-08-21 13:38
Duplicate of #50

Use standard viafabric instead. https://modrinth.com/mod/viafabric

**Closed by ishland** 2024-08-21 13:38 UTC
Labels: bug
